#!/bin/bash

# xrdp-kubuntu.sh - Complete xRDP setup script for Kubuntu with KDE/Plasma
# Author: Generated by Claude Code
# Description: Configures xRDP for optimal performance with Kubuntu/KDE

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration flags
INSTALL_XRDP=false
FIX_CURSOR=false
OPTIMIZE_PERFORMANCE=false
CONFIGURE_KDE=false
FIX_NETWORK_AUTH=false
SET_SOLID_BG=false
DISABLE_ENCRYPTION=false
PERSISTENT_SESSIONS=false
MINIMAL_KDE=false
BG_COLOR="#2b2b2b"
DRY_RUN=false

# Function to print colored output
print_msg() {
    echo -e "${2}${1}${NC}"
}

# Function to show usage
show_usage() {
    cat << EOF
Usage: $0 [OPTIONS]

OPTIONS:
    -h, --help              Show this help message
    --dry-run               Show what would be done without making changes
    --all                   Apply all configurations (recommended)
    --install               Install xRDP and required packages
    --cursor-fix            Fix black cursor with white box issue
    --performance           Apply performance optimizations
    --kde-config            Configure KDE/Plasma for xRDP
    --network-auth-fix      Remove network manager authentication prompts
    --solid-bg [COLOR]      Set solid background (default: #2b2b2b)
    --no-encryption         Disable encryption for LAN (better performance)
    --persistent-sessions   Enable persistent sessions (reconnect to same session)
    --minimal-kde           Make KDE minimal and snappy like Rocky Linux GNOME
    
EXAMPLES:
    $0 --dry-run --all                 # Preview all changes
    $0 --all                           # Apply all optimizations
    $0 --install --cursor-fix          # Install xRDP and fix cursor
    $0 --solid-bg "#404040"            # Set custom background color
    $0 --performance --no-encryption   # Performance mode for LAN

EOF
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_usage
            exit 0
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --all)
            INSTALL_XRDP=true
            FIX_CURSOR=true
            OPTIMIZE_PERFORMANCE=true
            CONFIGURE_KDE=true
            FIX_NETWORK_AUTH=true
            SET_SOLID_BG=true
            DISABLE_ENCRYPTION=true
            PERSISTENT_SESSIONS=true
            MINIMAL_KDE=true
            shift
            ;;
        --install)
            INSTALL_XRDP=true
            shift
            ;;
        --cursor-fix)
            FIX_CURSOR=true
            shift
            ;;
        --performance)
            OPTIMIZE_PERFORMANCE=true
            shift
            ;;
        --kde-config)
            CONFIGURE_KDE=true
            shift
            ;;
        --network-auth-fix)
            FIX_NETWORK_AUTH=true
            shift
            ;;
        --solid-bg)
            SET_SOLID_BG=true
            if [[ $2 =~ ^#[0-9a-fA-F]{6}$ ]]; then
                BG_COLOR=$2
                shift 2
            else
                shift
            fi
            ;;
        --no-encryption)
            DISABLE_ENCRYPTION=true
            shift
            ;;
        --persistent-sessions)
            PERSISTENT_SESSIONS=true
            shift
            ;;
        --minimal-kde)
            MINIMAL_KDE=true
            shift
            ;;
        *)
            print_msg "Unknown option: $1" "$RED"
            show_usage
            exit 1
            ;;
    esac
done

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   print_msg "This script should not be run as root" "$RED"
   exit 1
fi

# Function to show dry-run summary
show_dry_run_summary() {
    print_msg "\n=== DRY RUN MODE - No changes will be made ===" "$YELLOW"
    print_msg "\nThe following changes would be applied:\n" "$BLUE"
    
    if [ "$INSTALL_XRDP" = true ]; then
        print_msg "📦 INSTALL xRDP:" "$GREEN"
        echo "   - Install packages: xrdp, xorgxrdp, xcursor-themes, dmz-cursor-theme, imagemagick"
        echo "   - Enable and start xrdp and xrdp-sesman services"
        echo ""
    fi
    
    if [ "$FIX_CURSOR" = true ]; then
        print_msg "🖱️  FIX CURSOR:" "$GREEN"
        echo "   - Disable new_cursors in /etc/xrdp/xrdp.ini"
        echo "   - Set use_fastpath=none for Jump Desktop compatibility"
        echo "   - Configure DMZ-White cursor theme system-wide"
        echo "   - Add XCURSOR_CORE=1 and XCURSOR_DISCOVER=0 to ~/.xsessionrc"
        echo ""
    fi
    
    if [ "$OPTIMIZE_PERFORMANCE" = true ]; then
        print_msg "⚡ PERFORMANCE OPTIMIZATIONS:" "$GREEN"
        echo "   - Backup and optimize /etc/xrdp/xrdp.ini"
        echo "   - Enable bitmap caching and compression"
        echo "   - Set TCP buffer sizes to 512KB"
        echo "   - Configure network tuning in /etc/sysctl.d/99-xrdp-performance.conf"
        echo "   - Set max_bpp=24 for balanced quality/performance"
        echo "   - Allow X11 for all users in /etc/X11/Xwrapper.config"
        echo ""
    fi
    
    if [ "$CONFIGURE_KDE" = true ]; then
        print_msg "🖥️  CONFIGURE KDE/PLASMA:" "$GREEN"
        echo "   - Create optimized ~/.xsession for KDE"
        echo "   - Disable KDE compositing (KWIN_COMPOSE=N)"
        echo "   - Configure startplasma-x11 with --no-lockscreen"
        echo "   - Update /etc/xrdp/startwm.sh for KDE"
        echo "   - Disable network manager applet autostart"
        echo ""
    fi
    
    if [ "$FIX_NETWORK_AUTH" = true ]; then
        print_msg "🔓 FIX NETWORK AUTHENTICATION:" "$GREEN"
        echo "   - Create polkit rules to allow NetworkManager without password"
        echo "   - Configure /etc/polkit-1/rules.d/50-no-auth-networkmanager.rules"
        echo "   - Allow color management without authentication"
        echo "   - Restart polkit service"
        echo ""
    fi
    
    if [ "$SET_SOLID_BG" = true ]; then
        print_msg "🎨 SET SOLID BACKGROUND ($BG_COLOR):" "$GREEN"
        echo "   - Create 1x1 pixel image with color $BG_COLOR"
        echo "   - Apply wallpaper using plasma-apply-wallpaperimage"
        echo "   - Configure ~/.xsession to apply on each login"
        echo ""
    fi
    
    if [ "$DISABLE_ENCRYPTION" = true ]; then
        print_msg "🔐 DISABLE ENCRYPTION:" "$GREEN"
        echo "   - Set crypt_level=none in /etc/xrdp/xrdp.ini"
        echo "   - WARNING: Only use on trusted LAN connections!"
        echo ""
    fi
    
    if [ "$PERSISTENT_SESSIONS" = true ]; then
        print_msg "💾 PERSISTENT SESSIONS:" "$GREEN"
        echo "   - Set KillDisconnected=false in /etc/xrdp/sesman.ini"
        echo "   - Set DisconnectedTimeLimit=0 (no timeout)"
        echo "   - Allow reconnection to existing sessions"
        echo ""
    fi
    
    if [ "$MINIMAL_KDE" = true ]; then
        print_msg "🚀 MINIMAL KDE (Rocky Linux GNOME-like snappiness):" "$GREEN"
        echo "   - Reduce animation speed by 50%"
        echo "   - Disable Baloo file indexing service"
        echo "   - Disable blur effects"
        echo "   - Disable transparency/contrast effects"
        echo "   - Disable window shadows"
        echo "   - Disable smooth scrolling in applications"
        echo "   - Set faster menu/tooltip delays"
        echo "   - NOTE: Logout required for full effect"
        echo ""
    fi
    
    print_msg "=== END DRY RUN SUMMARY ===" "$YELLOW"
    exit 0
}

# Main installation function
install_xrdp() {
    print_msg "Installing xRDP and required packages..." "$BLUE"
    sudo apt update
    sudo apt install -y xrdp xorgxrdp
    
    # Install additional useful packages
    sudo apt install -y xcursor-themes dmz-cursor-theme imagemagick
    
    # Enable services
    sudo systemctl enable xrdp
    sudo systemctl enable xrdp-sesman
    sudo systemctl start xrdp
    sudo systemctl start xrdp-sesman
    
    print_msg "xRDP installation completed" "$GREEN"
}

# Fix cursor issues
fix_cursor() {
    print_msg "Applying cursor fixes..." "$BLUE"
    
    # Disable new cursors in xrdp.ini
    sudo sed -i 's/^new_cursors=.*/new_cursors=false/' /etc/xrdp/xrdp.ini 2>/dev/null || \
    echo "new_cursors=false" | sudo tee -a /etc/xrdp/xrdp.ini
    
    # Disable fastpath for better compatibility
    sudo sed -i 's/^use_fastpath=.*/use_fastpath=none/' /etc/xrdp/xrdp.ini
    
    # Set cursor theme
    mkdir -p ~/.icons/default
    cat > ~/.icons/default/index.theme << EOF
[Icon Theme]
Inherits=DMZ-White
EOF
    
    # Set system-wide cursor theme
    sudo update-alternatives --set x-cursor-theme /usr/share/icons/DMZ-White/cursor.theme 2>/dev/null || true
    
    # Add cursor environment variables
    echo "export XCURSOR_CORE=1" >> ~/.xsessionrc
    echo "export XCURSOR_DISCOVER=0" >> ~/.xsessionrc
    
    print_msg "Cursor fixes applied" "$GREEN"
}

# Performance optimizations
optimize_performance() {
    print_msg "Applying performance optimizations..." "$BLUE"
    
    # Backup original xrdp.ini
    sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.backup.$(date +%Y%m%d)
    
    # Create optimized xrdp.ini
    sudo bash -c 'cat > /etc/xrdp/xrdp.ini << "EOF"
# Performance optimized xrdp configuration

[Globals]
new_cursors=false
ini_version=1
fork=true
port=3389
tcp_nodelay=true
tcp_keepalive=yes
security_layer=negotiate
crypt_level=low

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
max_bpp=24
use_fastpath=none

# Performance tuning
tcp_send_buffer_bytes=524288
tcp_recv_buffer_bytes=524288
require_credentials=false

[Logging]
LogFile=xrdp.log
LogLevel=WARNING
EnableSyslog=false
SyslogLevel=WARNING

[Channels]
rdpdr=true
rdpsnd=false
drdynvc=true
cliprdr=true
rail=false
xrdpvr=false

[Session1]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20
EOF'
    
    # Network performance tuning
    sudo bash -c 'cat > /etc/sysctl.d/99-xrdp-performance.conf << "EOF"
# xRDP Performance tuning
vm.swappiness=10
net.core.rmem_max=12582912
net.core.wmem_max=12582912
net.ipv4.tcp_rmem=10240 87380 12582912
net.ipv4.tcp_wmem=10240 87380 12582912
net.ipv4.tcp_timestamps=0
net.ipv4.tcp_sack=0
net.core.netdev_max_backlog=5000
EOF'
    
    sudo sysctl -p /etc/sysctl.d/99-xrdp-performance.conf
    
    # Allow X11 for all users
    echo "allowed_users=anybody" | sudo tee -a /etc/X11/Xwrapper.config
    
    print_msg "Performance optimizations applied" "$GREEN"
}

# Configure KDE/Plasma
configure_kde() {
    print_msg "Configuring KDE/Plasma for xRDP..." "$BLUE"
    
    # Create .xsession file
    cat > ~/.xsession << 'EOF'
#!/bin/bash
# xRDP session configuration for KDE/Plasma

# Performance optimizations
unset DBUS_SESSION_BUS_ADDRESS
unset SESSION_MANAGER
export XCURSOR_CORE=1
export XCURSOR_DISCOVER=0
export QT_GRAPHICSSYSTEM=native
export QT_X11_NO_MITSHM=1

# Disable compositing for better RDP performance
export KWIN_COMPOSE=N
kwriteconfig5 --file kwinrc --group Compositing --key Enabled false 2>/dev/null || true

# Kill network management services that might prompt for authentication
killall nm-applet 2>/dev/null || true
killall plasma-nm 2>/dev/null || true

# Apply solid background if configured
if [ -f /tmp/solid-bg.png ]; then
    plasma-apply-wallpaperimage /tmp/solid-bg.png 2>/dev/null || true
fi

# Start KDE with performance settings
exec dbus-launch --exit-with-session startplasma-x11 --no-lockscreen
EOF
    chmod +x ~/.xsession
    
    # Update startwm.sh
    sudo bash -c 'cat > /etc/xrdp/startwm.sh << "EOF"
#!/bin/sh
if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG LANGUAGE
fi

# Cursor fix
export XCURSOR_CORE=1
export XCURSOR_DISCOVER=0

# Start the user session
if [ -r ~/.xsession ]; then
  . ~/.xsession
else
  startplasma-x11
fi
EOF'
    sudo chmod +x /etc/xrdp/startwm.sh
    
    # Disable network manager autostart for RDP
    mkdir -p ~/.config/autostart
    echo "[Desktop Entry]" > ~/.config/autostart/org.kde.plasma.networkmanagement.applet.desktop
    echo "Hidden=true" >> ~/.config/autostart/org.kde.plasma.networkmanagement.applet.desktop
    
    print_msg "KDE/Plasma configuration completed" "$GREEN"
}

# Fix network authentication prompts
fix_network_auth() {
    print_msg "Fixing network manager authentication prompts..." "$BLUE"
    
    # Create polkit rules
    sudo mkdir -p /etc/polkit-1/localauthority/50-local.d/
    sudo mkdir -p /etc/polkit-1/rules.d/
    
    # Allow NetworkManager for all users
    sudo bash -c 'cat > /etc/polkit-1/localauthority/50-local.d/45-allow-network-manager.pkla << "EOF"
[Allow NetworkManager for all users]
Identity=unix-user:*
Action=org.freedesktop.NetworkManager.*
ResultAny=yes
ResultInactive=yes
ResultActive=yes
EOF'
    
    # Create polkit rule
    sudo bash -c 'cat > /etc/polkit-1/rules.d/50-no-auth-networkmanager.rules << "EOF"
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.NetworkManager") == 0) {
        return polkit.Result.YES;
    }
});
EOF'
    
    # Allow color management
    sudo bash -c 'cat > /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla << "EOF"
[Allow Colord all Users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF'
    
    sudo systemctl restart polkit
    
    print_msg "Network authentication fixes applied" "$GREEN"
}

# Set solid background
set_solid_background() {
    print_msg "Setting solid background color: $BG_COLOR..." "$BLUE"
    
    # Check if imagemagick is installed
    if ! command -v convert &> /dev/null; then
        sudo apt install -y imagemagick
    fi
    
    # Create solid color image
    convert -size 1x1 xc:"$BG_COLOR" /tmp/solid-bg.png
    
    # Apply to current session if in KDE
    if [ -n "$DISPLAY" ]; then
        plasma-apply-wallpaperimage /tmp/solid-bg.png 2>/dev/null || true
    fi
    
    # Update xsession to apply on login
    if grep -q "Apply solid background" ~/.xsession 2>/dev/null; then
        print_msg "Solid background already configured in .xsession" "$YELLOW"
    else
        sed -i '/# Apply solid background/,/^fi/d' ~/.xsession 2>/dev/null || true
        sed -i '/exec dbus-launch/i\
# Apply solid background if configured\
if [ ! -f /tmp/solid-bg.png ]; then\
    convert -size 1x1 xc:'"'$BG_COLOR'"' /tmp/solid-bg.png 2>/dev/null || true\
fi\
plasma-apply-wallpaperimage /tmp/solid-bg.png 2>/dev/null || true\
' ~/.xsession
    fi
    
    print_msg "Solid background configured" "$GREEN"
}

# Disable encryption
disable_encryption() {
    print_msg "Disabling encryption for LAN performance..." "$BLUE"
    
    sudo sed -i 's/^crypt_level=.*/crypt_level=none/' /etc/xrdp/xrdp.ini
    
    print_msg "Encryption disabled (recommended for LAN only)" "$GREEN"
}

# Configure persistent sessions
configure_persistent_sessions() {
    print_msg "Configuring persistent sessions..." "$BLUE"
    
    # Keep sessions alive when disconnected
    sudo sed -i 's/^KillDisconnected=.*/KillDisconnected=false/' /etc/xrdp/sesman.ini
    
    # No timeout for disconnected sessions
    sudo sed -i 's/^DisconnectedTimeLimit=.*/DisconnectedTimeLimit=0/' /etc/xrdp/sesman.ini 2>/dev/null || \
    sudo sed -i '/\[Xorg\]/a\DisconnectedTimeLimit=0' /etc/xrdp/sesman.ini
    
    print_msg "Persistent sessions configured" "$GREEN"
}

# Configure minimal KDE for Rocky Linux GNOME-like performance
configure_minimal_kde() {
    print_msg "Configuring minimal KDE for maximum performance..." "$BLUE"
    
    # Reduce animation duration (0.5 = 50% speed, 0 = instant)
    kwriteconfig5 --file kdeglobals --group KDE --key AnimationDurationFactor 0.25
    print_msg "  - Animation speed increased 4x" "$GREEN"
    
    # Disable Baloo file indexing
    if command -v balooctl &> /dev/null; then
        balooctl disable 2>/dev/null || true
        balooctl purge 2>/dev/null || true
        print_msg "  - Baloo file indexing disabled" "$GREEN"
    else
        # Alternative method if balooctl not available
        kwriteconfig5 --file baloofilerc --group Basic --group Settings --key "Indexing-Enabled" false
        systemctl --user stop kde-baloo.service 2>/dev/null || true
        systemctl --user disable kde-baloo.service 2>/dev/null || true
        print_msg "  - Baloo file indexing disabled (via config)" "$GREEN"
    fi
    
    # Disable KDE visual effects
    kwriteconfig5 --file kwinrc --group Plugins --key blurEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key contrastEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_dimscreenEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_fadeEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_fadingpopupsEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_frozenappEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_fullscreenEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_loginEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_logoutEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_maximizeEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_morphingpopupsEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_scaleEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_sessionquitEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_squashEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_translucencyEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_windowapertureEnabled false
    kwriteconfig5 --file kwinrc --group Plugins --key slidingpopupsEnabled false
    print_msg "  - KDE visual effects disabled" "$GREEN"
    
    # Disable shadows
    kwriteconfig5 --file kwinrc --group Plugins --key kwin4_effect_shadowEnabled false
    print_msg "  - Window shadows disabled" "$GREEN"
    
    # Disable smooth scrolling
    kwriteconfig5 --file kdeglobals --group KDE --key ScrollbarLeftClickNavigatesByPage true
    kwriteconfig5 --file kcminputrc --group Mouse --key ScrollSpeed 3
    print_msg "  - Smooth scrolling disabled" "$GREEN"
    
    # Set faster tooltips and menu delays
    kwriteconfig5 --file kdeglobals --group KDE --key ToolTipDelay 100
    kwriteconfig5 --file kdeglobals --group KDE --key StartDragDist 4
    print_msg "  - Menu/tooltip delays reduced" "$GREEN"
    
    # Reduce systray animation
    kwriteconfig5 --file plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 2 --group General --key animationSpeed 1
    
    # Disable file previews in Dolphin
    kwriteconfig5 --file dolphinrc --group General --key ShowToolTips false
    kwriteconfig5 --file dolphinrc --group PreviewSettings --key Plugins ""
    print_msg "  - File manager previews disabled" "$GREEN"
    
    # Disable unnecessary KDE services
    systemctl --user disable kactivitymanagerd.service 2>/dev/null || true
    systemctl --user stop kactivitymanagerd.service 2>/dev/null || true
    print_msg "  - Unnecessary services disabled" "$GREEN"
    
    # Update the xsession to ensure compositing stays off
    if grep -q "KWIN_COMPOSE=N" ~/.xsession 2>/dev/null; then
        print_msg "  - Compositing already disabled in xsession" "$YELLOW"
    else
        sed -i '/# Disable compositing/i\
# Force minimal KDE settings\
export QT_QUICK_BACKEND=software' ~/.xsession 2>/dev/null || true
    fi
    
    # Try to reload KWin if in a KDE session
    if [ -n "$DISPLAY" ]; then
        qdbus org.kde.KWin /KWin reconfigure 2>/dev/null || true
    fi
    
    print_msg "Minimal KDE configuration completed" "$GREEN"
    print_msg "NOTE: Logout and login required for full effect!" "$YELLOW"
}

# Main execution
print_msg "=== xRDP Setup for Kubuntu ===" "$BLUE"

# Show dry-run summary if requested
if [ "$DRY_RUN" = true ]; then
    show_dry_run_summary
fi

# Execute selected configurations
if [ "$INSTALL_XRDP" = true ]; then
    install_xrdp
fi

if [ "$FIX_CURSOR" = true ]; then
    fix_cursor
fi

if [ "$OPTIMIZE_PERFORMANCE" = true ]; then
    optimize_performance
fi

if [ "$CONFIGURE_KDE" = true ]; then
    configure_kde
fi

if [ "$FIX_NETWORK_AUTH" = true ]; then
    fix_network_auth
fi

if [ "$SET_SOLID_BG" = true ]; then
    set_solid_background
fi

if [ "$DISABLE_ENCRYPTION" = true ]; then
    disable_encryption
fi

if [ "$PERSISTENT_SESSIONS" = true ]; then
    configure_persistent_sessions
fi

if [ "$MINIMAL_KDE" = true ]; then
    configure_minimal_kde
fi

# Restart services if any changes were made
if [ "$INSTALL_XRDP" = true ] || [ "$FIX_CURSOR" = true ] || [ "$OPTIMIZE_PERFORMANCE" = true ] || \
   [ "$DISABLE_ENCRYPTION" = true ] || [ "$PERSISTENT_SESSIONS" = true ]; then
    print_msg "Restarting xRDP services..." "$BLUE"
    sudo systemctl restart xrdp xrdp-sesman
    print_msg "xRDP services restarted" "$GREEN"
fi

# Show connection info
if [ "$INSTALL_XRDP" = true ] || [ "$OPTIMIZE_PERFORMANCE" = true ]; then
    IP=$(ip a | grep "inet " | grep -v "127.0.0.1" | head -1 | awk '{print $2}' | cut -d'/' -f1)
    print_msg "\n=== Connection Information ===" "$GREEN"
    print_msg "IP Address: $IP" "$GREEN"
    print_msg "Port: 3389" "$GREEN"
    print_msg "Username: $USER" "$GREEN"
    print_msg "Use your system password to connect" "$GREEN"
fi

print_msg "\n=== Setup Complete ===" "$GREEN"

# Show recommendations
if [ "$DISABLE_ENCRYPTION" = false ] && [ "$OPTIMIZE_PERFORMANCE" = true ]; then
    print_msg "\nTip: For better LAN performance, consider using --no-encryption" "$YELLOW"
fi

if [ "$PERSISTENT_SESSIONS" = false ]; then
    print_msg "Tip: Use --persistent-sessions to reconnect to the same session" "$YELLOW"
fi